export const languages = [
  { id: 'af', label: 'Afrikaans' },
  { id: 'sq', label: 'Albanian' },
  { id: 'am', label: 'Amharic' },
  { id: 'ar', label: 'Arabic' },
  { id: 'hy', label: 'Armenian' },
  { id: 'as', label: 'Assamese' },
  { id: 'ay', label: 'Aymara' },
  { id: 'az', label: 'Azerbaijani' },
  { id: 'bm', label: 'Bambara' },
  { id: 'eu', label: 'Basque' },
  { id: 'be', label: 'Belarusian' },
  { id: 'bn', label: 'Bengali' },
  { id: 'bho', label: 'Bhojpuri' },
  { id: 'bs', label: 'Bosnian' },
  { id: 'bg', label: 'Bulgarian' },
  { id: 'ca', label: 'Catalan' },
  { id: 'ceb', label: 'Cebuano' },
  { id: 'zh-CN', label: 'Chinese (Simplified)' },
  { id: 'zh-TW', label: 'Chinese (Traditional)' },
  { id: 'co', label: 'Corsican' },
  { id: 'hr', label: 'Croatian' },
  { id: 'cs', label: 'Czech' },
  { id: 'da', label: 'Danish' },
  { id: 'dv', label: 'Dhivehi' },
  { id: 'doi', label: 'Dogri' },
  { id: 'nl', label: 'Dutch' },
  { id: 'en', label: 'English' },
  { id: 'eo', label: 'Esperanto' },
  { id: 'et', label: 'Estonian' },
  { id: 'ee', label: 'Ewe' },
  { id: 'fil', label: 'Filipino (Tagalog)' },
  { id: 'fi', label: 'Finnish' },
  { id: 'fr', label: 'French' },
  { id: 'fy', label: 'Frisian' },
  { id: 'gl', label: 'Galician' },
  { id: 'ka', label: 'Georgian' },
  { id: 'de', label: 'German' },
  { id: 'el', label: 'Greek' },
  { id: 'gn', label: 'Guarani' },
  { id: 'gu', label: 'Gujarati' },
  { id: 'ht', label: 'Haitian Creole' },
  { id: 'ha', label: 'Hausa' },
  { id: 'haw', label: 'Hawaiian' },
  { id: 'he', label: 'Hebrew' },
  { id: 'hi', label: 'Hindi' },
  { id: 'hmn', label: 'Hmong' },
  { id: 'hu', label: 'Hungarian' },
  { id: 'is', label: 'Icelandic' },
  { id: 'ig', label: 'Igbo' },
  { id: 'ilo', label: 'Ilocano' },
  { id: 'id', label: 'Indonesian' },
  { id: 'ga', label: 'Irish' },
  { id: 'it', label: 'Italian' },
  { id: 'ja', label: 'Japanese' },
  { id: 'jv', label: 'Javanese' },
  { id: 'kn', label: 'Kannada' },
  { id: 'kk', label: 'Kazakh' },
  { id: 'km', label: 'Khmer' },
  { id: 'rw', label: 'Kinyarwanda' },
  { id: 'gom', label: 'Konkani' },
  { id: 'ko', label: 'Korean' },
  { id: 'kri', label: 'Krio' },
  { id: 'ku', label: 'Kurdish' },
  { id: 'ckb', label: 'Kurdish (Sorani)' },
  { id: 'ky', label: 'Kyrgyz' },
  { id: 'lo', label: 'Lao' },
  { id: 'la', label: 'Latin' },
  { id: 'lv', label: 'Latvian' },
  { id: 'ln', label: 'Lingala' },
  { id: 'lt', label: 'Lithuanian' },
  { id: 'lg', label: 'Luganda' },
  { id: 'lb', label: 'Luxembourgish' },
  { id: 'mk', label: 'Macedonian' },
  { id: 'mai', label: 'Maithili' },
  { id: 'mg', label: 'Malagasy' },
  { id: 'ms', label: 'Malay' },
  { id: 'ml', label: 'Malayalam' },
  { id: 'mt', label: 'Maltese' },
  { id: 'mi', label: 'Maori' },
  { id: 'mr', label: 'Marathi' },
  { id: 'mni-Mtei', label: 'Meiteilon (Manipuri)' },
  { id: 'lus', label: 'Mizo' },
  { id: 'mn', label: 'Mongolian' },
  { id: 'my', label: 'Myanmar (Burmese)' },
  { id: 'ne', label: 'Nepali' },
  { id: 'no', label: 'Norwegian' },
  { id: 'ny', label: 'Nyanja (Chichewa)' },
  { id: 'or', label: 'Odia (Oriya)' },
  { id: 'om', label: 'Oromo' },
  { id: 'ps', label: 'Pashto' },
  { id: 'fa', label: 'Persian' },
  { id: 'pl', label: 'Polish' },
  { id: 'pt', label: 'Portuguese (Portugal, Brazil)' },
  { id: 'pa', label: 'Punjabi' },
  { id: 'qu', label: 'Quechua' },
  { id: 'ro', label: 'Romanian' },
  { id: 'ru', label: 'Russian' },
  { id: 'sm', label: 'Samoan' },
  { id: 'sa', label: 'Sanskrit' },
  { id: 'gd', label: 'Scots Gaelic' },
  { id: 'nso', label: 'Sepedi' },
  { id: 'sr', label: 'Serbian' },
  { id: 'st', label: 'Sesotho' },
  { id: 'sn', label: 'Shona' },
  { id: 'sd', label: 'Sindhi' },
  { id: 'si', label: 'Sinhala (Sinhalese)' },
  { id: 'sk', label: 'Slovak' },
  { id: 'sl', label: 'Slovenian' },
  { id: 'so', label: 'Somali' },
  { id: 'es', label: 'Spanish' },
  { id: 'su', label: 'Sundanese' },
  { id: 'sw', label: 'Swahili' },
  { id: 'sv', label: 'Swedish' },
  { id: 'tl', label: 'Tagalog (Filipino)' },
  { id: 'tg', label: 'Tajik' },
  { id: 'ta', label: 'Tamil' },
  { id: 'tt', label: 'Tatar' },
  { id: 'te', label: 'Telugu' },
  { id: 'th', label: 'Thai' },
  { id: 'ti', label: 'Tigrinya' },
  { id: 'ts', label: 'Tsonga' },
  { id: 'tr', label: 'Turkish' },
  { id: 'tk', label: 'Turkmen' },
  { id: 'ak', label: 'Twi (Akan)' },
  { id: 'uk', label: 'Ukrainian' },
  { id: 'ur', label: 'Urdu' },
  { id: 'ug', label: 'Uyghur' },
  { id: 'uz', label: 'Uzbek' },
  { id: 'vi', label: 'Vietnamese' },
  { id: 'cy', label: 'Welsh' },
  { id: 'xh', label: 'Xhosa' },
  { id: 'yi', label: 'Yiddish' },
  { id: 'yo', label: 'Yoruba' },
  { id: 'zu', label: 'Zulu' },
]

export const languageNames = new Map(
  languages.map((language) => [language.id, language.label]),
)
